url: ''
baseurl: ''
title: 'Tyler Renfro'
jobTitle: 'UX Design'

plugins:
  - jekyll-postcss

postcss:
  cache: false

collections:
  portfolio:
    order:
      - stl-metro.md
      - payright.md
      - green-dining-finder.md
      - lockton.md
  research-artifacts:
    order:
      - heuristic-analysis.md
      - qualitative-surveys.md      
      - remote-usability-testing.md


exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
