url: 'https://www.tylerrenfro.com'
baseurl: ''
title: 'Tyler Renfro'
jobTitle: 'Product Designer'

plugins:
  - jekyll-postcss-v2

postcss:
  cache: false

collections:
  portfolio:
    order:
      - payflow.md
      - uswds-design-system.md
      - stl-metro.md
      - payright.md
      - green-dining-finder.md
      - lockton.md
  research-artifacts:
    order:
      - heuristic-evaluation.md
      - qualitative-surveys.md      
      - remote-usability-testing.md


exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
